services: 
  db: 
    image: postgres:13
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: poker_db
    volumes: 
    - db_data:/var/lib/postgresql/data

  api: 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
    - db
    ports:
    - "8080:8080"

volumes:
  db_data: