services: 
  db: 
    image: postgres:16
    restart: always
    environment: 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes: 
    - db_data:/var/lib/postgresql/data

  api: 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
    - db
    ports:
    - "8080:8080"

volumes:
  db_data: