services: 
  db: 
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: poker_db
    volumes: 
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api: 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
    - db
    ports:
    - "8080:8080"